
export const RECEIVE_PHOTO = 'RECEIVE_PHOTO';
export const REMOVE_PHOTO = 'REMOVE_PHOTO';


export const RECEIVE_GALLERY = 'RECEIVE_GALLERY';

export const CREATE_GALLERY = 'CREATE_GALLERY';




export const GALLERY_FORM_CHANGE_TITLE = 'GALLERY_FORM_CHANGE_TITLE';
export const GALLERY_FORM_ADD_PHOTO = 'GALLERY_FORM_ADD_PHOTO';
export const GALLERY_FORM_REMOVE_PHOTO = 'GALLERY_FORM_REMOVE_PHOTO';
export const GALLERY_FORM_CLEAR = 'GALLERY_FORM_CLEAR';
export const GALLERY_FORM_REORDER = 'GALLERY_FORM_REORDER';

export const RECEIVE_WECHAT_JSAPI = 'RECEIVE_WECHAT_JSAPI';


export const SET_APP_WECHAT_BROWSER = 'SET_APP_WECHAT_BROWSER';
