
export const RECEIVE_PHOTO = 'RECEIVE_PHOTO';


export const RECEIVE_GALLERY = 'RECEIVE_GALLERY';

export const CREATE_GALLERY = 'CREATE_GALLERY';




export const GALLERY_FORM_CHANGE_TITLE = 'GALLERY_FORM_CHANGE_TITLE';
export const GALLERY_FORM_ADD_PHOTO = 'GALLERY_FORM_ADD_PHOTO';
export const GALLERY_FORM_REMOVE_PHOTO = 'GALLERY_FORM_REMOVE_PHOTO';


