
export const RECEIVE_PHOTO = 'RECEIVE_PHOTO';
export const REMOVE_PHOTO = 'REMOVE_PHOTO';


export const RECEIVE_GALLERY = 'RECEIVE_GALLERY';
export const CREATE_GALLERY = 'CREATE_GALLERY';
export const UPDATE_GALLERY = 'UPDATE_GALLERY';

export const GALLERY_CREATE = 'GALLERY_CREATE';
export const GALLERY_UPDATE = 'GALLERY_UPDATE';




export const GALLERY_FORM_CHANGE_TITLE = 'GALLERY_FORM_CHANGE_TITLE';
export const GALLERY_FORM_ADD_PHOTO = 'GALLERY_FORM_ADD_PHOTO';
export const GALLERY_FORM_REMOVE_PHOTO = 'GALLERY_FORM_REMOVE_PHOTO';
export const GALLERY_FORM_CLEAR = 'GALLERY_FORM_CLEAR';
export const GALLERY_FORM_REORDER = 'GALLERY_FORM_REORDER';

export const RECEIVE_WECHAT_JSAPI = 'RECEIVE_WECHAT_JSAPI';


export const APP_SET_WECHAT_BROWSER = 'APP_SET_WECHAT_BROWSER';
export const APP_SET_CURRENT_USER = 'APP_SET_CURRENT_USER';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_GET = 'USER_GET';
